# Generated by Django 4.2.6 on 2023-10-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysinfo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemInfo',
        ),
    ]
